import {it,expect,vi} from 'vitest';
vi.mock('cloudflare:workers',()=>({WorkerEntrypoint:class{}}));
import{boundedMetadata,stagingRegistration,registrationEnabled,registrationTarget,registrationLedger}from'../../account/staging-registration';
const metadata={redirect_uris:['https://chatgpt.com/connector/oauth/SYNTHETIC_INSTANCE'],token_endpoint_auth_method:'none',grant_types:['authorization_code'],response_types:['code']};
const request=(body:unknown=metadata)=>new Request(registrationTarget.issuer+'/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
function fixture(){const values=new Map<string,any>();let queue=Promise.resolve();const storage={transaction:async(fn:any)=>{const result=queue.then(()=>fn({get:async(k:string)=>structuredClone(values.get(k)),put:async(k:string,v:any)=>values.set(k,structuredClone(v))}));queue=result.then(()=>{},()=>{});return result;}} as unknown as DurableObjectStorage;const calls:any[]=[],kv=new Map<string,string>();const env={ACCOUNT_ISSUER:registrationTarget.issuer,RESOURCE:registrationTarget.resource,STAGING_CLIENT_REGISTRATION:'enabled',ACCOUNT_BROWSER_SESSIONS:{idFromName:(n:string)=>{expect(n).toBe(registrationTarget.objectName);return n;},get:()=>({fetch:async(_:string,options:any)=>{const v=JSON.parse(options.body);calls.push(v.operation);try{return Response.json(await registrationLedger(storage,v));}catch{return new Response(null,{status:403});}}})},ACCOUNT_CONNECTOR_KV:{put:async(k:string,v:string)=>{calls.push('kv-put');kv.set(k,v);}}} as any;return{storage,values,calls,kv,env};}
it('strict registration metadata refuses unsafe callbacks/methods/grants',async()=>{for(const patch of [{redirect_uris:['https://evil.invalid/cb']},{redirect_uris:['https://chatgpt.com/connector/oauth/a?x=1']},{redirect_uris:['https://chatgpt.com/connector/oauth/a%2Fb']},{redirect_uris:['https://user@chatgpt.com/connector/oauth/a']},{redirect_uris:['https://chatgpt.com/connector_platform_oauth_redirect']},{token_endpoint_auth_method:'private_key_jwt'},{grant_types:['client_credentials']},{response_types:['token']},{scope:'repo write'},{client_name:{}}])await expect(boundedMetadata(request({...metadata,...patch}))).rejects.toThrow();});
it('unknown optional metadata never reaches the maintained handler',async()=>{expect(await boundedMetadata(request({...metadata,logo_uri:'javascript:alert(1)',client_uri:'https://evil.invalid',extra:{nested:'x'}}))).toEqual({...metadata,client_name:'Cartographer connection'});});
it('raw stream and declared size capped before admission',async()=>{const f=fixture();const r=await stagingRegistration(request({...metadata,extra:'x'.repeat(9000)}),f.env,{} as any);expect(r!.status).toBe(400);expect(f.calls).toHaveLength(0);});
it('off and production tuple refuse without state access',async()=>{for(const p of [{STAGING_CLIENT_REGISTRATION:'disabled'},{ACCOUNT_ISSUER:'https://account.klappy.dev'},{RESOURCE:'https://other.invalid/mcp'}]){const f=fixture();expect(registrationEnabled({...f.env,...p})).toBe(false);expect((await stagingRegistration(request(),{...f.env,...p},{} as any))!.status).toBe(404);expect(f.calls).toHaveLength(0);}});
it('maintained public DCR records durable ID before KV write and returns no-store response',async()=>{const f=fixture(),r=await stagingRegistration(request(),f.env,{} as any);expect(r!.status).toBe(201);const body=await r!.json() as any;expect(body).not.toHaveProperty('client_secret');expect(f.calls).toEqual(['registration-admit','registration-write-started','kv-put','registration-written']);expect(f.values.get('registration-ledger:v1')[0]).toMatchObject({clientId:body.client_id,state:'written'});expect(r!.headers.get('Cache-Control')).toBe('private, no-store');});
it('confidential response goes directly to requesting host; ledger stores no secret or hash',async()=>{const f=fixture(),r=await stagingRegistration(request({...metadata,token_endpoint_auth_method:'client_secret_basic'}),f.env,{} as any);const body=await r!.json() as any;expect(r!.status).toBe(201);expect(body.client_secret).toBeTruthy();const row=JSON.parse(f.kv.get('client:'+body.client_id)!);expect(row.clientSecret).not.toBe(body.client_secret);const ledger=JSON.stringify([...f.values.values()]);expect(ledger).not.toContain(body.client_secret);expect(ledger).not.toContain(row.clientSecret);});
it('lifetime budget serializes admission and rejects request eleven',async()=>{const f=fixture();const result=await Promise.all(Array.from({length:20},()=>stagingRegistration(request(),f.env,{} as any)));expect(result.filter(r=>r!.status===201)).toHaveLength(10);expect(result.filter(r=>r!.status===429)).toHaveLength(10);expect(f.kv.size).toBe(10);});
it('ambiguous KV write consumes slot and host retry is a separate retained client',async()=>{const f=fixture();let fail=true;f.env.ACCOUNT_CONNECTOR_KV.put=async(k:string,v:string)=>{f.kv.set(k,v);if(fail){fail=false;throw Error('SECRET_UNCERTAIN');}};const first=await stagingRegistration(request(),f.env,{} as any);expect(first!.status).toBe(503);expect(await first!.text()).not.toContain('SECRET');expect(f.values.get('registration-ledger:v1')[0].state).toBe('write-started');expect((await stagingRegistration(request(),f.env,{} as any))!.status).toBe(201);expect(f.kv.size).toBe(2);expect(f.values.get('registration-ledger:v1')).toHaveLength(2);});
it('no ledger reset/refund interface and corrupt ledger fails closed',async()=>{const f=fixture();f.values.set('registration-ledger:v1','corrupt');expect((await stagingRegistration(request(),f.env,{} as any))!.status).toBe(503);expect(f.kv.size).toBe(0);});
it('null, duplicate or inconsistent durable state never replenishes quota',async()=>{const attempt=crypto.randomUUID();for(const corrupt of [null,{},[{attempt,state:'admitted',clientId:'SYNTHETIC_CLIENT_'}],[{attempt,state:'written'}],[{attempt,state:'admitted'},{attempt,state:'admitted'}],[{attempt,state:'admitted',extra:true}],[{attempt:'not-uuid',state:'admitted'}]]){const f=fixture();f.values.set('registration-ledger:v1',corrupt);const before=structuredClone(corrupt);expect((await stagingRegistration(request(),f.env,{} as any))!.status).toBe(503);expect(f.values.get('registration-ledger:v1')).toEqual(before);expect(f.kv.size).toBe(0);}});
