import { expect, it, vi } from 'vitest';
vi.mock('cloudflare:workers', () => ({ WorkerEntrypoint: class {} }));
import { Miniflare } from 'miniflare';
import { build } from 'esbuild';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { harness } from './worker-harness';
import { BrowserSessions } from '../../account/browser-session';

async function fixture() {
  const h = await harness(), dir = await mkdtemp(join(tmpdir(), 'repository-start-'));
  const output = await build({ stdin: { contents: `
import worker,{AccountBrowserSessions as Browser,AccountGrantObject as Grant} from './account/broker';
import {accountAssertion} from './account/account-routes';
import {CompactEncrypt,compactDecrypt} from 'jose';
export class AccountBrowserSessions extends Browser{constructor(s,e){const original=e.ACCOUNT_GRANTS;const wrapped={idFromName:n=>original.idFromName(n),get:id=>({fetch:async(r)=>{const response=await original.get(id).fetch(r);if(new URL(r.url).pathname==='/oauth/start'){const fault=await s.storage.get('__fault');if(fault==='throw')throw Error('Injected transport loss after actual grant write');if(fault==='attach'){for(const [key,raw] of await s.storage.list({prefix:'session:v2:'})){const secret=new Uint8Array(32).fill(0xab),decoded=await compactDecrypt(raw,secret),session=JSON.parse(new TextDecoder().decode(decoded.plaintext));if(session.repositoryState){session.repositoryState.expiresAt=0;await s.storage.put(key,await new CompactEncrypt(new TextEncoder().encode(JSON.stringify(session))).setProtectedHeader(decoded.protectedHeader).encrypt(secret));}}}}return response;}})};super(s,{...e,ACCOUNT_GRANTS:wrapped});this.saved=s;}async fetch(r){const b=await r.clone().json();if(b.operation==='__fault'){await this.saved.storage.put('__fault',b.value);return Response.json({ok:true});}if(b.operation==='__marker'){if('value'in b)await this.saved.storage.put('repository-start:v2:in-flight',b.value);return Response.json(await this.saved.storage.get('repository-start:v2:in-flight')??null);}return super.fetch(r);}}
export class AccountGrantObject extends Grant{constructor(s,e){super(s,e);this.saved=s;this.mode='normal';this.entered=false;}async fetch(r){const p=new URL(r.url).pathname;
if(p==='/__mode'){this.mode=await r.text();return Response.json({ok:true});}
if(p==='/__entered')return Response.json({entered:this.entered});
if(p==='/__release'){this.release?.();return Response.json({ok:true});}
if(p==='/__pending')return Response.json({pending:await this.saved.storage.get('oauth-pending'),count:await this.saved.storage.get('__count')??0});
if(p==='/oauth/start'){this.entered=true;await this.saved.storage.put('__count',(await this.saved.storage.get('__count')??0)+1);if(this.mode==='pause')await new Promise(resolve=>this.release=resolve);const result=await super.fetch(r);if(this.mode==='error')return new Response('platform timeout',{status:504});if(this.mode==='malformed')return Response.json({authorizationUrl:'https://evil.invalid/'});if(this.mode==='truncated')return new Response('{',{headers:{'Content-Type':'application/json'}});return result;}return super.fetch(r);}}
export default{async fetch(r,e,c){const p=new URL(r.url).pathname;const authority=e.ACCOUNT_BROWSER_SESSIONS.get(e.ACCOUNT_BROWSER_SESSIONS.idFromName('account-authority-v2'));if(p==='/__op')return authority.fetch(r);if(p==='/__auth'){const b=await r.json();const s=await(await authority.fetch('https://internal.invalid/',{method:'POST',body:JSON.stringify({operation:'load',handle:b.handle})})).json();return Response.json(await accountAssertion(s,e,b.handle));}return worker.fetch(r,e,c);}}
`, resolveDir: process.cwd(), loader: 'ts' }, bundle: true, write: false, format: 'esm', platform: 'browser', external: ['cloudflare:workers'] });
  const bindings = { ...Object.fromEntries(Object.entries(h.env).filter(([, v]) => typeof v === 'string')), BROWSER_SESSION_KEY_HEX: 'ab'.repeat(32), ACCOUNT_LOGIN_CALLBACK: h.env.ACCOUNT_ISSUER + '/account/callback' };
  const start = () => new Miniflare({ modules: true, script: output.outputFiles[0].text, compatibilityDate: '2026-06-16', host: '127.0.0.1', port: 0, cf: false, bindings, kvNamespaces: ['ACCOUNT_CONNECTOR_KV'], durableObjects: { ACCOUNT_BROWSER_SESSIONS: { className: 'AccountBrowserSessions', useSQLite: true }, ACCOUNT_GRANTS: { className: 'AccountGrantObject', useSQLite: true } }, durableObjectsPersist: dir, outboundService: () => { throw Error('No external I/O allowed during local start'); } });
  let mf = start();
  const raw = (body: Record<string, unknown>) => mf.dispatchFetch(h.env.ACCOUNT_ISSUER + '/__op', { method: 'POST', body: JSON.stringify(body), redirect: 'manual' });
  const op = async (body: Record<string, unknown>): Promise<any> => { const r = await raw(body); expect(r.status).toBe(200); return r.json(); };
  const issue = async (browser: string) => { const p = await op({ operation: 'begin', handle: browser }); const transaction = { kind: 'identity-bootstrap', state: crypto.randomUUID(), verifier: 'INERT', callback: bindings.ACCOUNT_LOGIN_CALLBACK, expiresAt: Date.now() + 300000 }; await op({ operation: 'start', handle: browser, nonce: p.nonce, transaction }); const proof = await op({ operation: 'consume', handle: browser, nonce: p.nonce, state: transaction.state }); const active = await op({ operation: 'activate', githubId: 1001, proof: proof.proof }); const s = await op({ operation: 'load', handle: active.handle }); return { ...active, browser, subject: s.identity.subject }; };
  const prepare = async (a: any, purpose: string) => { const s = await op({ operation: 'load', handle: a.handle }); let ref: string | undefined;
    if (purpose === 'connector') ref = (await op({ operation: 'continuation-create', handle: a.browser, activeHandle: a.handle, intent: { clientId: 'fixture', redirectUri: 'https://client.example.test/callback', state: 'original', responseType: 'code', codeChallenge: 'c'.repeat(43), codeChallengeMethod: 'S256', resource: h.env.RESOURCE, scope: ['repository:read'] } })).ref;
    const lease = await op({ operation: purpose === 'account' ? 'repository-account-prepare' : 'repository-connector-prepare', handle: a.handle, nonce: s.csrf, continuationRef: ref });
    const auth = await (await mf.dispatchFetch(h.env.ACCOUNT_ISSUER + '/__auth', { method: 'POST', body: JSON.stringify({ handle: a.handle }) })).json() as { assertion: string };
    return { operation: 'repository-start', handle: a.handle, purpose, lease: lease.lease, continuationRef: ref, assertion: auth.assertion };
  };
  const cancel = async (a: any, attempt: any) => { const s = await op({ operation: 'load', handle: a.handle }); return op(attempt.purpose === 'account' ? { operation: 'repository-account-cancel', handle: a.handle, lease: attempt.lease, nonce: s.csrf } : { operation: 'continuation-cancel', handle: a.browser, activeHandle: a.handle, ref: attempt.continuationRef, nonce: s.csrf }); };
  const grant = async (a: any, path: string, body?: string) => { const ns = await mf.getDurableObjectNamespace('ACCOUNT_GRANTS'); return ns.get(ns.idFromName(a.subject)).fetch('https://internal.invalid/' + path, { method: body === undefined ? 'GET' : 'POST', body }); };
  return { raw, op, issue, prepare, cancel, grant, page: (a: any) => mf.dispatchFetch(h.env.ACCOUNT_ISSUER + '/account', { headers: { Cookie: '__Host-account_session=' + a.handle }, redirect: 'manual' }), restart: async () => { await mf.dispose(); mf = start(); }, dispose: async () => { await mf.dispose(); await rm(dir, { recursive: true, force: true }); } };
}

it.each([['account', 'account'], ['account', 'connector'], ['connector', 'account'], ['connector', 'connector']])('canceled %s start released after newer %s start cannot overwrite actual grant Pending', async (oldPurpose, newPurpose) => {
  const f = await fixture(); try { const a = await f.issue('a'.repeat(64)), old = await f.prepare(a, oldPurpose); await f.cancel(a, old); const next = await f.prepare(a, newPurpose); expect((await f.raw(next)).status).toBe(200); const before = await (await f.grant(a, '__pending')).json(); expect((await f.raw(old)).status).toBe(403); expect(await (await f.grant(a, '__pending')).json()).toEqual(before); expect((before as any).count).toBe(1); } finally { await f.dispose(); }
}, 30000);

it.each([['account', 'cancel'], ['connector', 'cancel'], ['account', 'signout'], ['connector', 'signout'], ['account', 'replacement'], ['connector', 'replacement'], ['account', 'newstart'], ['connector', 'newstart']])('native %s start holds event gate through actual GrantDO Pending write and %s', async (purpose, action) => {
  const f = await fixture(); try { const a = await f.issue('b'.repeat(64)), attempt = await f.prepare(a, purpose), captured = await f.op({ operation: 'load', handle: a.handle }); await f.grant(a, '__mode', 'pause'); const starting = f.raw(attempt);
    let entered = false; for (let i = 0; i < 100 && !entered; i++) { entered = ((await (await f.grant(a, '__entered')).json()) as any).entered; if (!entered) await new Promise(r => setTimeout(r, 5)); } expect(entered).toBe(true);
    let finished = false; const cancel = (action === 'cancel' ? f.op(purpose === 'account' ? { operation: 'repository-account-cancel', handle: a.handle, lease: attempt.lease, nonce: captured.csrf } : { operation: 'continuation-cancel', handle: a.browser, activeHandle: a.handle, ref: attempt.continuationRef, nonce: captured.csrf }) : action === 'replacement' ? f.op({ operation: 'continuation-create', handle: a.browser, activeHandle: a.handle, intent: { clientId: 'fixture', redirectUri: 'https://client.example.test/callback', state: 'replacement', responseType: 'code', codeChallenge: 'c'.repeat(43), codeChallengeMethod: 'S256', resource: 'https://navigator.example.test/mcp', scope: ['repository:read'] } }) : action === 'newstart' ? f.raw(attempt).then(r => { expect(r.status).toBe(403); }) : f.op({ operation: 'signout', handle: a.handle, nonce: captured.csrf })).then(r => { finished = true; return r; }); await new Promise(r => setTimeout(r, 25)); expect(finished).toBe(false);
    await f.grant(a, '__release'); const started = await starting; expect(started.status).toBe(200); const url = new URL(((await started.json()) as any).authorizationUrl); await cancel; expect((await f.raw({ operation: 'repository-state', handle: a.handle, nonce: url.searchParams.get('state'), consume: true, continuationRef: attempt.continuationRef })).status).toBe(action === 'newstart' ? 200 : 403); expect(await f.op({ operation: 'repository-start-status' })).toEqual({ blocked: false });
  } finally { await f.dispose(); }
}, 30000);

it.each(['error', 'malformed', 'truncated', 'throw'])('uncertain %s completion persists through native orderly restart, Cancel/signout and blocks other browsers', async mode => {
  const f = await fixture(); try { const a = await f.issue('c'.repeat(64)), b = await f.issue('d'.repeat(64)), c = await f.issue('f'.repeat(64)), otherAccount = await f.prepare(b, 'account'), otherConnector = await f.prepare(c, 'connector'), old = await f.prepare(a, 'account'); if (mode === 'throw') await f.op({ operation: '__fault', value: 'throw' }); else await f.grant(a, '__mode', mode); expect((await f.raw(old)).status).toBe(403); expect(await f.op({ operation: 'repository-start-status' })).toEqual({ blocked: true }); const encrypted = await f.op({ operation: '__marker' }); expect(encrypted).not.toContain(a.subject); expect(encrypted).not.toContain(old.lease);
    await f.restart(); expect(await f.op({ operation: 'repository-start-status' })).toEqual({ blocked: true }); const page = await f.page(a); expect(await page.text()).toContain('New repository connections are temporarily unavailable pending verified recovery'); await f.cancel(a, old); const s = await f.op({ operation: 'load', handle: a.handle }); await f.op({ operation: 'signout', handle: a.handle, nonce: s.csrf });
    const pendingBefore = await (await f.grant(b, '__pending')).json();
    for (const validPrepared of [otherAccount, otherConnector]) expect((await f.raw(validPrepared)).status).toBe(403);
    expect(await (await f.grant(b, '__pending')).json()).toEqual(pendingBefore);
    expect(await f.op({ operation: '__marker' })).toBe(encrypted); expect(((await (await f.grant(b, '__pending')).json()) as any).count).toBe(1);
  } finally { await f.dispose(); }
}, 30000);

it.each([null, '', 0, false, 'corrupt'])('native malformed marker %j never becomes absence', async value => { const f = await fixture(); try { await f.op({ operation: '__marker', value }); expect(await f.op({ operation: 'repository-start-status' })).toEqual({ blocked: true }); const a = await f.issue('e'.repeat(64)); expect((await f.raw({ operation: 'repository-account-prepare', handle: a.handle, nonce: a.csrf })).status).toBe(403); } finally { await f.dispose(); } }, 30000);

it('exact completion rejects missing/partial/old attempts; known completed write with failed attachment cannot replay', async () => {
  const data = new Map<string, unknown>();
  const storage: any = { get: async (key: string) => structuredClone(data.get(key)), put: async (key: string | Record<string, unknown>, value: unknown) => { if (typeof key === 'string') data.set(key, structuredClone(value)); else for (const [k, v] of Object.entries(key)) data.set(k, structuredClone(v)); }, delete: async (key: string) => data.delete(key), list: async ({ prefix, limit }: any) => new Map([...data].filter(([k]) => k.startsWith(prefix)).sort(([a], [b]) => a.localeCompare(b)).slice(0, limit)), transaction: async (fn: any) => { const before = structuredClone(data); try { return await fn(storage); } catch (error) { data.clear(); for (const [k, v] of before) data.set(k, v); throw error; } } };
  const store = new BrowserSessions(storage, new Uint8Array(32).fill(0xab)), browser = '9'.repeat(64), p = await store.begin(browser), tx = { kind: 'identity-bootstrap' as const, state: 'state', verifier: 'INERT', callback: 'https://account.example.test/account/callback', expiresAt: Date.now() + 300000 };
  await store.start(browser, p.nonce, tx); const a = await store.activate(1001, (await store.consume(browser, p.nonce, tx.state)).proof), lease = await store.prepareAccountRepository(a.handle, a.csrf), marker = await store.admitRepositoryStart(a.handle, lease.lease, 'account'), before = structuredClone(data);
  for (const invalid of [{}, { ...marker, attempt: undefined }, { ...marker, attempt: 'f'.repeat(64) }, { ...marker, version: 2 }, { ...marker, extra: true }]) { await expect(store.completeRepositoryStart(invalid as any)).rejects.toThrow(); expect(data).toEqual(before); }
  // Synthetic storage composition, not native crash evidence: expiry cannot clear uncertainty.
  vi.useFakeTimers(); try { vi.setSystemTime(Date.now() + 300001); expect(await store.repositoryStartStatus()).toEqual({ blocked: true }); await store.completeRepositoryStart(marker); expect(await store.repositoryStartStatus()).toEqual({ blocked: false }); await expect(store.attachAccountRepository(a.handle, lease.lease, 'state')).rejects.toThrow(); await expect(store.admitRepositoryStart(a.handle, lease.lease, 'account')).rejects.toThrow(); } finally { vi.useRealTimers(); }
});

it('native recognized real start completion then injected attachment expiry clears only known-complete marker without redirect or replay', async () => {
  const f = await fixture(); try { const a = await f.issue('8'.repeat(64)), attempt = await f.prepare(a, 'account'); await f.op({ operation: '__fault', value: 'attach' }); const result = await f.raw(attempt); expect(result.status).toBe(403); expect(await result.text()).not.toContain('authorizationUrl'); expect(await f.op({ operation: 'repository-start-status' })).toEqual({ blocked: false }); const before = await (await f.grant(a, '__pending')).json(); expect((before as any).count).toBe(1); expect((await f.raw(attempt)).status).toBe(403); expect(await (await f.grant(a, '__pending')).json()).toEqual(before); } finally { await f.dispose(); }
}, 30000);
