import { expect, it, vi } from 'vitest';
import { CompactEncrypt, compactDecrypt } from 'jose';
import { BrowserSessions } from '../../account/browser-session';
import { entryPage } from '../../account/account-ui';
class Storage {
 data=new Map<string,unknown>();
 async get<T>(key:string){return structuredClone(this.data.get(key))as T|undefined;}
 async put(key:string|Record<string,unknown>,value?:unknown){if(typeof key==='string')this.data.set(key,structuredClone(value));else for(const[k,v]of Object.entries(key))this.data.set(k,structuredClone(v));}
 async delete(key:string){return this.data.delete(key);}
 async list<T>({prefix,limit}:{prefix:string;limit:number}){return new Map([...this.data].filter(([k])=>k.startsWith(prefix)).sort(([a],[b])=>a.localeCompare(b)).slice(0,limit))as Map<string,T>;}
 async transaction<T>(fn:(tx:any)=>Promise<T>){const before=structuredClone(this.data);try{return await fn(this);}catch(e){this.data=before;throw e;}}
}
const browser='a'.repeat(64),key=new Uint8Array(32).fill(0xab);
const transaction=()=>({kind:'identity-bootstrap'as const,state:crypto.randomUUID(),verifier:'INERT',callback:'https://fixture.invalid/account/callback',expiresAt:Date.now()+300000});
async function fixture(){const storage=new Storage(),store=new BrowserSessions(storage as any,key);const issue=async(b=browser,active?:string,id=1001)=>{const p=await store.begin(b,active),tx=transaction();await store.start(b,p.nonce,tx);return store.activate(id,(await store.consume(b,p.nonce,tx.state)).proof);};return{storage,store,issue};}
async function mutate(storage:Storage,prefix:string,fn:(v:any)=>void){const[k,raw]=[...storage.data].find(([k])=>k.startsWith(prefix))!;const d=await compactDecrypt(raw as string,key),v=JSON.parse(new TextDecoder().decode(d.plaintext));fn(v);await storage.put(k,await new CompactEncrypt(new TextEncoder().encode(JSON.stringify(v))).setProtectedHeader(d.protectedHeader).encrypt(key));}
it.each(['idle','absolute','missing-cookie'])('authoritative %s identity constrains both begin modes without action authority',async mode=>{
 for(const restart of [false,true]){const f=await fixture(),a=await f.issue();if(mode!=='missing-cookie')await mutate(f.storage,'session:v2:',s=>{s.createdAt=Date.now()-28800001;s.verifiedAt=s.createdAt;if(mode==='absolute'){s.absoluteUntil=Date.now()-1;s.idleUntil=s.absoluteUntil;}else{s.absoluteUntil=Date.now()+1000;s.createdAt=s.absoluteUntil-28800000;s.verifiedAt=s.createdAt;s.idleUntil=Date.now()-1;}});
 const before=structuredClone(f.storage.data);expect((await f.store.entry(browser,mode==='missing-cookie'?undefined:a.handle)).kind).toBe('verify');expect(f.storage.data).toEqual(before);
 const p=await f.store.begin(browser,mode==='missing-cookie'?undefined:a.handle,undefined,restart),tx=transaction();await f.store.start(browser,p.nonce,tx,undefined,restart);await expect(f.store.activate(1002,(await f.store.consume(browser,p.nonce,tx.state)).proof)).rejects.toThrow();
 }
});
it.each([undefined,null,'',false,'corrupt'])('dangling or corrupt active record %j never becomes anonymous',async value=>{const f=await fixture(),a=await f.issue(),k=[...f.storage.data.keys()].find(k=>k.startsWith('session:v2:'))!;if(value===undefined)await f.storage.delete(k);else await f.storage.put(k,value);const before=structuredClone(f.storage.data);await expect(f.store.entry(browser,a.handle)).rejects.toThrow();for(const restart of[false,true])await expect(f.store.begin(browser,undefined,undefined,restart)).rejects.toThrow();expect(f.storage.data).toEqual(before);});
it('supplied nonexistent session is not anonymous even on an empty browser ledger',async()=>{const f=await fixture();for(const restart of[false,true])await expect(f.store.begin(browser,'f'.repeat(64),undefined,restart)).rejects.toThrow();expect(f.storage.data.size).toBe(0);expect((await f.store.entry(browser)).kind).toBe('anonymous');});
it('entry-to-begin stale handle/replacement and supplied browser disagreement deny without mutation',async()=>{const f=await fixture(),a=await f.issue();expect((await f.store.entry(browser,a.handle)).kind).toBe('active');await f.issue(browser,a.handle);const before=structuredClone(f.storage.data);await expect(f.store.begin(browser,a.handle)).rejects.toThrow();await expect(f.store.entry('b'.repeat(64),a.handle)).rejects.toThrow();expect(f.storage.data).toEqual(before);});
it('revoked entry gives only eligible supplied-record signout proof and explicit signout retains replacement-ending semantics',async()=>{const f=await fixture(),a=await f.issue(),other=await f.issue('b'.repeat(64));await f.store.signout(other.handle,other.csrf,true);const before=structuredClone(f.storage.data),entry=await f.store.entry(browser,a.handle);expect(entry).toEqual({kind:'revoked',signoutCsrf:a.csrf});expect(f.storage.data).toEqual(before);await expect(f.store.begin(browser,a.handle)).rejects.toThrow();await f.store.signout(a.handle,('signoutCsrf' in entry ? entry.signoutCsrf! : ''));const fresh=await f.issue();const captured=await f.store.entry(browser,fresh.handle);expect(captured.kind).toBe('active');const replacement=await f.issue(browser,fresh.handle);await f.store.signout(fresh.handle,fresh.csrf);await expect(f.store.load(replacement.handle)).rejects.toThrow();});
it('revoked absolute-expired entry never promises an unusable signout action',async()=>{const f=await fixture(),a=await f.issue(),other=await f.issue('b'.repeat(64));await f.store.signout(other.handle,other.csrf,true);vi.useFakeTimers();try{vi.setSystemTime(Date.now()+28800001);expect(await f.store.entry(browser,a.handle)).toEqual({kind:'revoked'});}finally{vi.useRealTimers();}});

it.each([null,false,'',0,{},[]])('malformed persisted account epoch %j cannot classify active or expose signout proof',async value=>{const f=await fixture(),a=await f.issue(),s=await f.store.load(a.handle);await f.storage.put('epoch:v2:'+s.identity.subject,value);const before=structuredClone(f.storage.data);await expect(f.store.entry(browser,a.handle)).rejects.toThrow();await expect(f.store.begin(browser,a.handle)).rejects.toThrow();expect(f.storage.data).toEqual(before);});
it('entry ref/ABA classification is read-only and never infers a different live slot',async()=>{const f=await fixture(),a=await f.issue(),intent={clientId:'fixture',redirectUri:'https://client.invalid/cb',state:'original',responseType:'code'as const,codeChallenge:'c'.repeat(43),codeChallengeMethod:'S256'as const,resource:'https://resource.invalid/mcp',scope:['repository:read']as ['repository:read']};const first=await f.store.createContinuation(browser,intent,a.handle);const snapshot=structuredClone(f.storage.data);await expect(f.store.entry(browser,a.handle,'f'.repeat(64))).rejects.toThrow();await expect(f.store.entry(browser,a.handle)).rejects.toThrow();expect(f.storage.data).toEqual(snapshot);await f.store.retireContinuation(browser,first.ref);expect((await f.store.entry(browser,a.handle,first.ref)).kind).toBe('active');const pending=await f.store.begin(browser,a.handle,first.ref,true),tx=transaction();const replacement=await f.store.createContinuation(browser,intent,a.handle);await f.store.retireContinuation(browser,replacement.ref);const after=structuredClone(f.storage.data);await expect(f.store.start(browser,pending.nonce,tx,first.ref,true)).rejects.toThrow();expect(f.storage.data).toEqual(after);});
it('entry inspection and recovery rendering retain global uncertain-start status',async()=>{const f=await fixture(),a=await f.issue();await f.storage.put('repository-start:v2:in-flight','corrupt-retained-marker');const before=structuredClone(f.storage.data);expect((await f.store.entry(browser,a.handle)).kind).toBe('active');expect(await f.store.repositoryStartStatus()).toEqual({blocked:true});expect(f.storage.data).toEqual(before);const html=entryPage('verify',undefined,true);expect(html).toContain('New repository connections are temporarily unavailable because the previous connection could not be confirmed');expect(html).toContain('Signing in or signing out does not resolve this issue.');expect(html).not.toContain('corrupt-retained-marker');});
it.each([false,true])('continuation-only identity rejects malformed epoch for terminal=%s',async terminal=>{const f=await fixture(),a=await f.issue(),s=await f.store.load(a.handle),flow=await f.store.createContinuation(browser,{clientId:'fixture',redirectUri:'https://client.invalid/cb',state:'original',responseType:'code',codeChallenge:'c'.repeat(43),codeChallengeMethod:'S256',resource:'https://resource.invalid/mcp',scope:['repository:read']},a.handle);if(terminal)await mutate(f.storage,'continuation:v2:',c=>{c.stage='spent';delete c.intent;});const ledgerKey=[...f.storage.data.keys()].find(k=>k.startsWith('browser:v2:'))!,ledger=await f.storage.get<any>(ledgerKey);await f.storage.delete(ledger.active);delete ledger.active;await f.storage.put(ledgerKey,ledger);expect((await f.store.entry(browser,undefined,flow.ref)).kind).toBe(terminal?'terminal':'live');await f.storage.put('epoch:v2:'+s.identity.subject,null);const before=structuredClone(f.storage.data);await expect(f.store.entry(browser,undefined,flow.ref)).rejects.toThrow();await expect(f.store.begin(browser,undefined,flow.ref,terminal)).rejects.toThrow();expect(f.storage.data).toEqual(before);});
