import {it,expect,vi} from 'vitest';
vi.mock('cloudflare:workers',()=>({WorkerEntrypoint:class{}}));
import {createAccountRoutes} from '../../account/account-routes';
import {accountPage} from '../../account/account-ui';
it('public exit stays on staging and query parameters cannot choose its destination',async()=>{const routes=createAccountRoutes();const response=await routes(new Request('https://account-staging.klappy.dev/account/public?next=https://evil.invalid'),{RESOURCE:'https://cartographer-staging.klappy.dev/mcp',PRIVATE_ACTIVATION:'disabled'} as any,async()=>new Response(null,{status:403}));expect(response!.status).toBe(200);const html=await response!.text();expect(html).toContain('href="https://cartographer-staging.klappy.dev/explore.html"');expect(html).not.toContain('evil.invalid');expect(html).toContain('name="viewport"');expect(html).toContain('charset="utf-8"');expect(response!.headers.get('Cache-Control')).toBe('private, no-store');expect(response!.headers.get('Set-Cookie')).toBeNull();});
it('public exit remains available with absent or unrecognized configuration',async()=>{for(const RESOURCE of [undefined,'javascript:alert(1)','https://evil.invalid/mcp','https://cartographer-staging.klappy.dev/mcp?next=evil']){const response=await createAccountRoutes()(new Request('https://account.example/account/public'),{RESOURCE} as any,async()=>new Response());expect(response!.status).toBe(200);expect(await response!.text()).toContain('href="https://cartographer.klappy.dev/explore.html"');}});
it('connect and its broad permission disclosure stay primary while session controls remain available',()=>{const html=accountPage({subject:'github:123',csrf:'nonce',connected:false});expect(html.indexOf('upstream writes')).toBeLessThan(html.indexOf('Connect repository access'));expect(html.indexOf('Connect repository access')).toBeLessThan(html.indexOf('<details>'));expect(html).toContain('<summary>Browser session details</summary>');expect(html).toContain('Sign out of all browsers');expect(html).toContain('not from GitHub');expect(html).toContain('eight hours');expect(html).toContain('does not end existing connector sessions');});

it('uncertain connection offers status check without implying rollback or requesting retry',()=>{const html=accountPage({subject:'github:123',csrf:'nonce',repositoryLease:{lease:'synthetic',phase:'committing'}});expect(html).toContain('may have completed');expect(html).toContain('href=\"/account\">Check connection status');expect(html).not.toContain('rollback');});
