export const accountStyles = 'body{font:18px system-ui;line-height:1.6;max-width:42rem;margin:auto;padding:2rem;color:#17212b;background:#f6f8fa}main{overflow-wrap:anywhere;background:white;padding:2rem;border:1px solid #ccd3db;border-radius:1rem}button,a{font:inherit}button{padding:.6rem 1rem;margin:.25rem 0}a{color:#075bb5}form{margin:1rem 0}';
export const escape = (value: string) => value.replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]!));
export function standalonePage(nonce: string, ref?: string) {
  const fields = `<input type="hidden" name="csrf" value="${escape(nonce)}"><input type="hidden" name="restart" value="standalone"><input type="hidden" name="continuation" value="${escape(ref ?? '')}">`;
  return `<!doctype html><html lang="en"><meta charset="utf-8"><title>Separate account sign-in</title><style>${accountStyles}</style><main><h1>Start a separate account sign-in</h1><p>This verifies your GitHub identity and requests permission to read your GitHub profile (read:user). Repository access requires separate authorization. It does not resume or authorize the old connector request. Start a new connection from your connector when ready.</p><form method="post" action="/account/signin">${fields}<button>Sign in with GitHub</button></form><form method="post" action="/account/signin/restart/cancel">${fields}<button>Cancel sign-in</button></form><a href="/account/public">Continue with public access</a></main></html>`;
}
export function accountPage(input: { subject?: string; csrf?: string; connected?: boolean; loginCsrf?: string; continuationRef?: string } = {}) {
  const continuation = input.continuationRef ? `<input type="hidden" name="continuation" value="${escape(input.continuationRef)}">` : '';
  const form = (path: string, label: string) => `<form method="post" action="${path}"><input type="hidden" name="csrf" value="${escape(input.csrf ?? input.loginCsrf ?? '')}">${continuation}<button>${label}</button></form>`;
  return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Account access</title><style>${accountStyles}</style><main><h1>Account access</h1>${input.subject ? `<p>Signed in as ${escape(input.subject)}</p><p>${input.connected ? 'Repository access connected.' : 'Repository access is not connected.'}</p><p>GitHub’s repository permission is broad: it can allow upstream writes across repositories you can access. This service permits only reads and keeps credentials on the server.</p>${input.connected ? form('/account/disconnect', 'Disconnect repository access') : form('/account/repositories/connect', 'Connect repository access')}${form('/account/signout', 'Sign out')}${form('/account/revoke-all-local-browser-sessions', 'Revoke all local browser sessions')}<p>Browser sign-out does not end existing connector sessions or repository grants. Disconnect repository access separately to revoke those grants.</p><p>Browser sessions expire after 30 minutes idle or eight hours total. New repository or connector consent requires GitHub sign-in within five minutes. GitHub-side identity revocation is not continuously checked after the identity credential is discarded.</p><p><a href="/account/signin">Verify again with the same GitHub account</a>. Recovery requires that same GitHub identity; no email or manual account merge is available. Sign out before switching accounts.</p>` : input.loginCsrf ? `<p>GitHub verifies your identity. This sign-in requests only read:user; repository access requires separate, broader consent.</p><form method="post" action="/account/signin"><input type="hidden" name="csrf" value="${escape(input.loginCsrf)}">${continuation}<button>Sign in with GitHub</button></form>` : '<p>Sign-in is currently unavailable while the secure provider connection is completed.</p><button disabled>Sign in with GitHub</button>'}${input.continuationRef ? form('/account/continuation/cancel', 'Cancel connection') : ''}<p><a href="/account/public">Continue with public access</a></p></main></html>`;
}
export function browserHeaders() { return { 'Cache-Control': 'private, no-store', 'CDN-Cache-Control': 'no-store', 'Cloudflare-CDN-Cache-Control': 'no-store', 'Content-Security-Policy': "default-src 'none'; style-src 'unsafe-inline'; form-action 'self'; frame-ancestors 'none'; base-uri 'none'", 'Referrer-Policy': 'no-referrer', 'X-Content-Type-Options': 'nosniff' }; }
export function consentPage(input: { client: string; resource: string; csrf: string; authorizationUrl: string; continuationRef?: string }) {
  return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Approve connection</title><style>${accountStyles}</style><main><h1>Approve connection</h1><p>${escape(input.client)} requests repository read access through ${escape(input.resource)}.</p><p>This does not change GitHub’s broad upstream repository grant. Provider credentials stay on the server.</p><form method="post" action="/authorize"><input type="hidden" name="csrf" value="${escape(input.csrf)}">${input.continuationRef ? `<input type="hidden" name="continuation" value="${escape(input.continuationRef)}">` : `<input type="hidden" name="authorizationUrl" value="${escape(input.authorizationUrl)}">`}<button name="decision" value="approve">Approve connection</button><button name="decision" value="deny">Cancel</button></form><p><a href="/account/public">Continue with public access</a></p></main></html>`;
}
